# Generated by Django 5.1.3 on 2024-11-27 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userType', models.CharField(max_length=10)),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('MidInit', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionId', models.IntegerField(primary_key=True, serialize=False)),
                ('classId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.class')),
                ('TA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TA_Scheduler.user')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TA_Scheduler.user'),
        ),
        migrations.CreateModel(
            name='userPrivateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.user')),
            ],
        ),
        migrations.CreateModel(
            name='userPublicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.user')),
            ],
        ),
    ]
