# Generated by Django 5.1.3 on 2024-12-03 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='assignments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='schedule',
            field=models.CharField(default='Default Schedule', max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='max_capacity',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='section',
            name='schedule',
            field=models.CharField(default='Default Schedule', max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='TA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.user'),
        ),
        migrations.AlterField(
            model_name='section',
            name='classId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.class'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
