# Generated by Django 5.1.3 on 2024-12-13 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0003_remove_class_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='TA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TA_Scheduler.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='MidInit',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fName',
            field=models.CharField(default='First', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='lName',
            field=models.CharField(default='Last', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprivateinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.user'),
        ),
        migrations.AlterField(
            model_name='userpublicinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduler.user'),
        ),
    ]
