# Generated by Django 5.1.3 on 2024-12-13 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0004_alter_section_ta_alter_user_midinit_alter_user_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='TA_Scheduler.user'),
        ),
    ]
